### ISSUE TITLE
Filtered Computer list showing vaild computers within AD

### ISSUE THREAD

**Issue by khizar786** [shadowguardian507-irl/ComputersVsAdmin-docker#1]
Hi,

I have found a bug in the system where all filtered computers are showing as vaild within AD domain. 

Regards 
Khizar Bahsir

**Comment by shadowguardian507-irl** [comment]
Thanks for the bug report.

This issue has now been resolved as of app version V1.0.1

The bug was fixed in change https://github.com/shadowguardian507-irl/ComputersVsAdmin-docker/commit/c1daa4be50bc47cb5822ff8f8996022beabe6b66
